// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5d19TDzNTZswlmtyVRU4VWbnFP3M0uL8',
    appId: '1:117202129029:web:56b84ea8578129169359ec',
    messagingSenderId: '117202129029',
    projectId: 'apocalypse-eca02',
    authDomain: 'apocalypse-eca02.firebaseapp.com',
    storageBucket: 'apocalypse-eca02.appspot.com',
    measurementId: 'G-H778T0X291',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPTbtzWsQqqsWuiDHOm4yFJNSqnwmY-QE',
    appId: '1:117202129029:android:ca9843eb280415689359ec',
    messagingSenderId: '117202129029',
    projectId: 'apocalypse-eca02',
    storageBucket: 'apocalypse-eca02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw6apO3l9Ppyh2XHGm-Ml56UKYVfTFrnI',
    appId: '1:117202129029:ios:68805ff59c937f149359ec',
    messagingSenderId: '117202129029',
    projectId: 'apocalypse-eca02',
    storageBucket: 'apocalypse-eca02.appspot.com',
    iosBundleId: 'com.example.apocalypsea2sv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw6apO3l9Ppyh2XHGm-Ml56UKYVfTFrnI',
    appId: '1:117202129029:ios:68805ff59c937f149359ec',
    messagingSenderId: '117202129029',
    projectId: 'apocalypse-eca02',
    storageBucket: 'apocalypse-eca02.appspot.com',
    iosBundleId: 'com.example.apocalypsea2sv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5d19TDzNTZswlmtyVRU4VWbnFP3M0uL8',
    appId: '1:117202129029:web:585c2543c28253db9359ec',
    messagingSenderId: '117202129029',
    projectId: 'apocalypse-eca02',
    authDomain: 'apocalypse-eca02.firebaseapp.com',
    storageBucket: 'apocalypse-eca02.appspot.com',
    measurementId: 'G-PJEJ53X8BX',
  );
}
